product/urls.py
from django.urls import path, include
from product import views
from rest_framework import routers
from . import views

# from django.conf.urls import include, url

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'products', views.ProductViewSet)
router.register(r'customuser', views.CustomUserViewSet)
router.register(r'angulardata', views.AngularViewSet)


urlpatterns = [

    # path("",views.home),
    # path("",views.homeIndex,name="homeIndex"),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('customuser/', views.index, name='customuser'),
    path('angulardata/', views.angulardata),
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view,name="login"),
    path("logout/",views.logout_view,name="logout"),
    # path('home/',views.home ),
    path('indexpage/', views.indexpage),

    path('userreg/', views.ruser, name="userreg"),
    path('productreg/', views.rproduct, name="productreg"),

    path('showUser/', views.showUser),
    path('showProduct/', views.showProduct),

    path('userProduct/<int:id>', views.userProduct),

    path("userProfile/<int:id>", views.userProfile),

    path('updateUser/<int:id>', views.updateUser, name="updateUser"),
    path('updateProduct/<int:id>', views.updateProduct, name="updateProduct"),

    path('deleteUser/<int:id>', views.destroyUser, name="deleteUser"),
    path('deleteProduct/<int:id>', views.destroyProduct, name="deleteProduct"),


]

project/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
# from django.contrib.auth.models import User
# from rest_framework import routers, serializers, viewsets


urlpatterns = i18n_patterns(

    path("", include("product.urls")),
    path('admin/', admin.site.urls),
    url(r'^', include('cms.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
# from django.contrib.auth.models import User
# from django.db.models.signals import post_save
from cms.models.pluginmodel import CMSPlugin
# from aldryn_bootstrap3 import model_fields
from django.utils.translation import gettext_lazy as _

# Create your models here.

class User(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    mobile = models.CharField(max_length=10)
    birthdate = models.DateField()
    city = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    is_verified = models.BooleanField(default=False)
    created_at= models.DateTimeField(auto_now_add=True,blank=False)
    updated_at = models.DateTimeField(auto_now = True, blank=False)

    class Meta:
        db_table = "user"

    def __str__(self):
        return self.firstname + ' ' + self.lastname


class Product(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products')
    product_name = models.CharField(max_length=50)
    product_type = models.CharField(max_length=50)

    class Meta:
        db_table = "product"

    def __str__(self):
        return self.product_name




class Hello(CMSPlugin):
    guest_name = models.CharField(max_length=50, default='Guest')


class Menu_Item(CMSPlugin):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to="menu_items")
    price = models.CharField(max_length=200)
    description = models.TextField()
    url = models.CharField(max_length=200)

    def __unicode__(self):
        return "%s" % (self.name,)

class Employee(CMSPlugin):
    fname = models.CharField(max_length=200)
    lname = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    description = models.TextField()

    def __unicode__(self):
        return "%s" % (self.fname,)


# class UserCustom_Plugin(CMSPlugin):
#     fname = models.CharField(max_length=200)
#     items_per_page = models.PositiveIntegerField(
#         verbose_name= _('Items per page'),
#         null=False,
#         blank=False,
#         help_text= _('Show number of items per page'),
#     )
#
#     def __str__(self):
#         return str(self.items_per_page)

class User_Custom_Plugin(CMSPlugin):
    items_per_page = models.PositiveIntegerField(
        verbose_name= _('Items per page'),
        null=False,
        blank=False,
        help_text= _('Show number of items per page'),
        default=0
    )

    def __str__(self):
        return str(self.items_per_page)

product/forms.py
from django import forms
from .models import Product, User
from django.contrib.auth.forms import UserCreationForm


# class SignUpForm(UserCreationForm):
#
#     first_name = forms.CharField(max_length=100, help_text='First Name')
#     last_name = forms.CharField(max_length=100, help_text='Last Name')
#     email = forms.EmailField(max_length=150, help_text='Email')
#
#     class Meta:
#
#         model = User
#         fields = ('username', 'first_name', 'last_name',
#                   'email', 'password1', 'password2')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = "__all__"

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

product/views.py
# from django.shortcuts import render, redirect, HttpResponseRedirect, reverse
from .forms import ProductForm
from .models import *
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
# from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
# from .forms import SignUpForm
from .forms import UserForm
# from sekizai.context import SekizaiContext
#from django.template import RequestContext
from .serializers import UserSerializer, ProductSerializer, CustomUserSerializer, AngularSerializer
import django_filters.rest_framework
from rest_framework import generics, filters, viewsets, permissions


# Create your views here.


class UserViewSet(viewsets.ModelViewSet, generics.ListAPIView):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('firstname')
    serializer_class = UserSerializer
    filter_backends = [filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['=firstname', '=email']

    # class CustomSearchFilter(filters.SearchFilter):
        # def get_search_fields(self, view, request):
        #     if request.query_params.get('firstname'):
        #         return ['firstname']
        #     return super(CustomSearchFilter, self).get_search_fields(view, request)
    ordering_fields = ['firstname', 'lastname', 'city', 'email']
    permission_classes = [permissions.IsAuthenticated]


class ProductViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Product.objects.all().order_by('product_name')
    serializer_class = ProductSerializer
    filter_backends = [filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['=product_name', '=product_type']
    ordering_fields = ['product_name', 'product_type']
    permission_classes = [permissions.IsAuthenticated]


class CustomUserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all().order_by('firstname')
    serializer_class = CustomUserSerializer

class AngularViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all().order_by('firstname')
    serializer_class = AngularSerializer



def index(request):
    return render(request, 'product/customTable.html')


def angulardata(request):
    return render(request,'product/angulardata.html')


def indexpage(request):
     return render(request, "base.html")


def homeIndex(request):
    return render(request, "product/homeIndex.html")


def home(request):
    return render(request, "product/home.html")


def logout_view(request):
    logout(request)
    return redirect('/')


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            print("==============================")
            return redirect('/login')
    else:
        form = UserCreationForm()
    return render(request, 'product/signup.html', {'form': form})

    # form = SignUpForm(request.POST)
    # if form.is_valid():
    #     user = form.save()
    #     user.refresh_from_db()
    #     user.profile.first_name = form.cleaned_data.get('first_name')
    #     user.profile.last_name = form.cleaned_data.get('last_name')
    #     user.profile.email = form.cleaned_data.get('email')
    #     user.save()
    #     username = form.cleaned_data.get('username')
    #     password = form.cleaned_data.get('password1')
    #     user = authenticate(username=username, password=password)
    #     login(request, user)
    #     return redirect('homeIndex')
    # else:
    #     form = SignUpForm()
    # return render(request, 'product/signup.html', {'form': form})


################ login forms###################################################
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/')
    else:
        form = AuthenticationForm()
    return render(request, 'product/login.html', {'form': form})


def ruser(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/showUser')

            except:
                pass
    else:
        form = UserForm()
        return render(request, 'product/userIndex.html', {'form': form})


def rproduct(request):
    if request.method == "POST":
        form = ProductForm(request.POST)

        if form.is_valid():
            try:
                form.save()
                return redirect('/showProduct')
            except:
                pass
    else:
        form = ProductForm()
    return render(request, 'product/productIndex.html', {'form': form})

from django.shortcuts import render as render_to_response
from django.template import RequestContext

#@login_required(login_url='/login/')
def showUser(request):
    if request.user.is_authenticated:

        products = Product.objects.all()
        # pk = request.GET.get('order_by')
        sort = request.GET.get('sort', '')
        desc = request.GET.get('desc', False)
        cuser = User.objects.all()

        ctx = {}
        url_parameter = request.GET.get("q")

        if url_parameter:
            users = cuser.filter(firstname__istartswith=url_parameter)
        else:
            users = cuser

        if sort:
            if desc:
                users = users.order_by("-"+sort)
            else:
                users = users.order_by(sort)

        # user_list = User.objects.all()
        page = request.GET.get('page', 1)

        paginator = Paginator(users, 2)
        try:
            users = paginator.page(page)
        except PageNotAnInteger:
            users = paginator.page(1)
        except EmptyPage:
            users = paginator.page(paginator.num_pages)


        ctx["users"] = users
        ctx["desc"] = desc
        ctx["q"] = url_parameter
        ctx['sorts'] = sort
        if request.is_ajax():
            html = render_to_string(
                template_name="product/showUserSearch.html", context={"users": users, 'sorts': sort, 'desc' : desc, 'q': url_parameter}
            )
            data_dict = {"html_from_view": html}
            return JsonResponse(data=data_dict, safe=False)

        return render(request, "product/showUser.html", context=ctx)

    else:
        return redirect('/')


def userProfile(request, id):
    if request.user.is_authenticated:
        userp = User.objects.get(id=id)
        return render(request, 'product/user_profile.html', {"user": userp})
    else:
        return redirect('/')

def showProduct(request):
    if request.user.is_authenticated:

        products = Product.objects.all()
        if request.GET.get('user_id', ''):
            user = User.objects.get(id=request.GET.get('user_id'))
            products = user.products.all()
            # products = products.filter(user_id=y)

        page = request.GET.get('page', 1)

        paginator = Paginator(products, 5)
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        return render(request, "product/showProduct.html", {'products': products})
    else:
        return redirect('/')


def showUserProduct(request, id):
    prod = Product.objects.filter(user_id=id)
    return render(request, "product/showProduct.html", {'key2': prod})


def editUser(request, id):
    euser = User.objects.get(id=id)
    return render(request, 'product/editUser.html', {'user': euser})


def editProduct(request, id):
    eproduct = Product.objects.get(id=id)
    return render(request, 'product/editProduct.html', {'prod': eproduct})


# @login_required(login_url='/login/')
def updateUser(request, id):
    if request.user.is_authenticated:

        uuser = User.objects.get(id=id)
        if request.method == "POST":
            form = UserForm(request.POST, instance=uuser)
            if form.is_valid():
                form.save()
                return redirect('/showUser')
        form = UserForm(instance=uuser)

        return render(request, 'product/editUser.html', {'users': form, "id": id})
    else:
        return redirect('/')


def updateProduct(request, id):
    if request.user.is_authenticated:

        uproduct = Product.objects.get(id=id)
        if request.method == "POST":
            form = ProductForm(request.POST, instance=uproduct)
            print("=============================")
            print(form)
            if form.is_valid():
                form.save()
                return redirect('/showProduct')
        form = ProductForm(instance=uproduct)

        return render(request, 'product/editProduct.html', {'prod': form, 'id': id})
    else:
        return redirect('/')


def destroyUser(request, id):
    User.objects.get(id=id).delete()
    data = {
        'deleted': True
    }
    return JsonResponse(data)

def destroyProduct(request, id):
    dproduct = Product.objects.get(id=id)
    dproduct.delete()
    return redirect("/showProduct")

def userProduct(request, id):
    usproduct = Product.objects.filter(user_id=id)
    uname=User.objects.get(id=id)
    return render(request, 'product/userProduct.html', {'prod': usproduct, 'id': uname})

product/templates/product/angulardata.html
{% extends "base.html" %}
{% load i18n static %}

    {% block js %}
        <script src = "https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
        <script type="text/javascript" src="{% static 'javascript/angularjs/angular.js' %}"></script>
        <script type="text/javascript" src="{% static 'javascript/angularjs/angular-resource.js' %}"></script>
        <script type="text/javascript" src="{% static 'javascript/angularjs/angular-route.js' %}"></script>
        <script type="text/javascript" src="{% static 'javascript/angularjs/angular-sanitize.js' %}"></script>
        <script>
         var mainApp = angular.module("mainApp", []);

         mainApp.controller('studentController', function($scope) {
            $scope.student = {
               firstName: "Mahesh",
               lastName: "Parashar",
               fees:500,

               subjects:[
                  {name:'Physics',marks:70},
                  {name:'Chemistry',marks:80},
                  {name:'Math',marks:65},
                  {name:'English',marks:75},
                  {name:'Hindi',marks:67}
               ],

               fullName: function() {
                  var studentObject;
                  studentObject = $scope.student;
                  return studentObject.firstName + " " + studentObject.lastName;
               }
            };
         });
      </script>

{% endblock js %}
{% block content %}



      <div ng-app = "mainApp" ng-controller = "studentController">

         <table class="table table-striped table-bordered" border="1px solid black"  >
            <tr>
               <td>Enter first name:</td>
               <td><input type = "text" ng-model = "student.firstName"></td>
            </tr>
            <tr>
               <td>Enter last name: </td>
               <td>
                  <input type = "text" ng-model = "student.lastName">
               </td>
            </tr>
            <tr>
               <td>Name: </td>
               <td>{{student.fullName}} </td>
            </tr>
            <tr>
               <td>Subject:</td>

               <td>
                  <table class="table table-striped table-bordered" border="1px solid black" >
                     <tr>
                        <th>Name</th>.
                        <th>Marks</th>
                     </tr>
                     <tr ng-repeat = "subject in student.subjects">
                        <td>{{ subject.name}} </td>
                        <td>{{ subject.marks }}</td>
                     </tr>
                  </table>
               </td>
            </tr>
         </table>
      </div>



{% endblock content %}

product/templates/product/customTable.html
{% extends "base.html" %}
{% load i18n static %}
{% block content %}

                    <table id="customuser" class="table table-striped table-bordered" border="1px solid black" align="center" data-server-side="true" data-ajax="/api/customuser/?format=datatables">
                        <thead class="thead-dark">
                            <tr>
                                <th data-data="id">Id</th>
                                <th data-data="firstname">firstname</th>
                                <th data-data="lastname">Lastname</th>
                                <th data-data="mobile">mobile</th>
                                <th data-data="birthdate">birthdate</th>
                                <th data-data="city">city</th>
                                <th data-data="email">email</th>
                                <th data-data="products">products</th>
                            </tr>
                        </thead>
                    </table>

{% endblock content %}

{%  block footer %}

        <script src="//code.jquery.com/jquery-1.12.4.js"></script>
        <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        <script src="//cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
        <script>$(document).ready(function() {$('#customuser').DataTable();});</script>



{% endblock footer %}

product/templates/product/editProduct.html
{% extends "base.html" %}
{% load i18n static %}

{% block content %}

<form method="POST" class="post-form" action="{% url 'updateProduct' id=id %}">
        {% csrf_token %}
        <div class="container" align="center">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                <h3>Update Details</h3>
                </div>
            </div>


            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Product User :</label>
                <div class="col-sm-4">
                    {{ prod.user_id }}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Product Name:</label>
                <div class="col-sm-4">
                    {{ prod.product_name }}
                    {{ prod.errors }}


                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Product Type:</label>
                <div class="col-sm-4">
                    {{ prod.product_type }}
                </div>
            </div>


            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

product/templates/product/editUser.html
{% extends "base.html" %}
{% load i18n static %}

{% block content %}
<form method="POST" class="post-form" action="{% url 'updateUser' id=id %}">
    {% csrf_token %}

    <div class="container" >
        <br>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
            <h3>Update Details</h3>
            </div>
        </div>


<!--        <div class="form-group row">-->
<!--            <label class="col-sm-2 col-form-label">User Id:</label>-->
<!--            <div class="col-sm-4">-->
<!--                <input type="text" name="id" id="id_id" required maxlength="20" value="{{user.id}}"/>-->
<!--            </div>-->
<!--        </div>-->

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">First Name:</label>
            <div class="col-sm-4">
                {{users.firstname}}
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Last Name:</label>
            <div class="col-sm-4">
                {{users.lastname}}
            </div>
        </div>

<!--        <div class="form-group row">-->
<!--            <label class="col-sm-2 col-form-label">Product Name:</label>-->
<!--            <div class="col-sm-4">-->
<!--                <input type="text" name="product_name" id="id_product_name" required maxlength="100" value="{{user.product_name}}" />-->
<!--            </div>-->
<!--        </div>-->


        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Birth Date:</label>
            <div class="col-sm-4">
                {{users.birthdate}}
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Mobile:</label>
            <div class="col-sm-4">
                {{ users.mobile }}
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">City:</label>
            <div class="col-sm-4">
                {{ users.city }}
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Email:</label>
            <div class="col-sm-4">
                {{ users.email }}
            </div>
        </div>



        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

product/templates/product/employee_data.html
<table class="table" border="1px solid black" >
    <thead class="thead-dark">

        <th>First Name</th>
        <th>Last name</th>
        <th>Description</th>
        <th>City</th>

    </thead>
 <tbody>
  <tr>

        <td>{{ fname }}</a></td>
        <td>{{ lname }}</td>
      <td>{{ description }}</td>
      <td>{{ city }}</td>

    </tr>

  </table>

product/templates/product/login.html
{% extends "base.html" %}
{% load i18n static %}



{% block content %}
    <h2>Log In</h2>
    <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Login</button>
  </form>
{% endblock content %}

product/templates/product/menu_item.html
    <div class="row justify-content-center pt-3 pt-md-4">
      <div class="col-12 col-xl-11">
    <table width="480" border="1" cellpadding="2">
        <tr>
            <td><img  height="160px" width="160px" src="{{ image.url }}" alt="{{ name }}"></td>
            <td><img  height="160px" width="160px" src="{{ image.url }}" alt="{{ name }}"></td>
            <td><img  height="160px" width="160px" src="{{ image.url }}" alt="{{ name }}"></td>
        </tr>
    </table>
        <h1 class="ds_elem name">{{ name }}</h1>
    <h3><h1 class="ds_elem name">{{ price }}</h1></h3>
    <p class="ds_elem desc">
        {{ description }}
        <a class="more_link" href="{{ url }}">More...</a>
    </p>
      </div>
      </div>

product/templates/product/showUser.html
{% extends "base.html" %}
{% load i18n static %}
{% load cms_tags menu_tags sekizai_tags %}



{% block content %}

<br>
<div id="replaceable-content" class="">

<table class="table table-striped table-bordered table-sm" border="1px solid black" align="center">


    <thead class="thead-dark">

    <tr>
<!--        <th>User ID</th>-->
        {% if desc %}
            {% if q %}
                <th><a href="/showUser/?q={{q}}">First Name</a></th>
            {% else %}
                <th><a href="/showUser/?sort=firstname">First Name</a></th>
            {% endif %}
        {% else %}
            {% if q %}
                <th><a href="/showUser/?desc=true&q={{q}}">First Name</a></th>
            {% else %}
                <th><a href="/showUser/?desc=true&sort=firstname">First Name</a></th>
            {% endif %}
        {% endif %}


        {% if desc %}
            {% if q %}
                <th><a href="/showUser/?q={{q}}">Last Name</a></th>
            {% else %}
                <th><a href="/showUser/?sort=lastname">Last Name</a></th>
            {% endif %}
        {% else %}
            {% if q %}
                <th><a href="/showUser/?desc=true&q={{q}}">Last Name</a></th>
            {% else %}
                <th><a href="/showUser/?desc=true&sort=lastname">Last Name</a></th>
            {% endif %}
        {% endif %}

<!--        <th>Product Name</th>  -->
        <th>Birth date</th>  
        <th>Mobile</th>  
        {% if desc %}
            {% if q %}
                <th><a href="/showUser/?q={{q}}">City</a></th>
            {% else %}
                <th><a href="/showUser/?sort=city">City</a></th>
            {% endif %}
        {% else %}
            {% if q %}
                <th><a href="/showUser/?desc=true&q={{q}}">City</a></th>
            {% else %}
                <th><a href="/showUser/?desc=true&sort=city">City</a></th>
            {% endif %}
        {% endif %}

        {% if desc %}
            {% if q %}
                <th><a href="/showUser/?q={{q}}">Email</a></th>
            {% else %}
                <th><a href="/showUser/?sort=email">Email</a></th>
            {% endif %}
        {% else %}
            {% if q %}
                <th><a href="/showUser/?desc=true&q={{q}}">Email</a></th>
            {% else %}
                <th><a href="/showUser/?desc=true&sort=email">Email</a></th>
            {% endif %}
        {% endif %}

        <th>Edit</th>
        <th>Delete</th>
         <th>Products</th>
    </tr>  
    </thead>
    <tbody>
    {% for user in users %}
    <tr id="user-{{user.id}}">
<!--        <td>{{ user.id }}</td>-->
        <td><a href="/userProfile/{{ user.id }}">{{ user.firstname }}</a></td>
        <td>{{ user.lastname }}</td>
<!--        <td>{{ user.product_name }}</td>-->
        <td>{{ user.birthdate }}</td>
        <td>{{ user.mobile }}</td>
        <td>{{ user.city }}</td>
        <td>{{ user.email }}</td>
        <td>

<!--            <a href="/updateUser/{{ user.id }}"><span class="btn btn-danger form-control" >Edit</span></a>-->
            <form action="/updateUser/{{ user.id }}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ user.id }}">
                <input type="submit" class="btn btn-danger form-control" value="edit">
            </form>
<!--            <a href="/deleteUser/{{ user.id }}">Delete</a>-->
        </td>
        <td>
<!--            <form method="POST">-->
<!--                {% csrf_token %}-->
<!--                <input type="submit" onclick="deleteUser({{user.id}})" value="delete">-->
<!--            </form>-->
            <button class="btn btn-danger form-control" onclick="deleteUser({{user.id}})">DELETE</button>
        </td>
<!--        <td><a href="/showProduct/?user_id={{ user.id }}">Products</a></td>-->

        <td>
            <form action="/showProduct/?user_id={{ user.id }}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{user.id}}">
                <input class="btn btn-danger form-control" type="submit" value="Products">
            </form>
        </td>

    </tr>  
    {% endfor %}
    </tbody>

</table>
{% if users.has_other_pages %}
  <ul class="pagination navbar navbar-light-bordered">
    {% if users.has_previous %}
      <li><a href="?page={{ users.previous_page_number }}&sort={{sorts}}{% if desc %}&desc=true&sort={{sorts}}{% endif %}{% if q %}&q={{q}}{% endif %}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in users.paginator.page_range %}
      {% if users.number == i %}
        <li class="active"><span>{{ i }}<span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}&sort={{sorts}}{% if desc %}&desc=true&sort={{sorts}}{% endif %}{% if q %}&q={{q}}{% endif %}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if users.has_next %}

      <li><a href="?page={{ users.next_page_number }}&sort={{sorts}}{% if desc %}&desc=true&sort={{sorts}}{% endif %}{% if q %}&q={{q}}{% endif %}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
</div>
<center><a href="{% url 'userreg' %}" class="btn btn-primary">Add New Record</a></center>


{% endblock content %}

product/templates/product/sidebar_right.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="content">
        {% placeholder "content" %}
    </div>
    <div class="sidebar">
        {% placeholder "sidebar" %}
    </div>
{% endblock content %}

product/templates/product/template_2.html
{% extends "base.html" %}
{% load cms_tags %}

{% block base_content %}
  {% placeholder template_1_content %}
{% endblock %}